---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr-db
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
    - name: onepassword-connect
      namespace: external-secrets
  interval: 1h
  path: ./src/kubernetes/components/cnpg-database
  postBuild:
    substitute:
      APP: prowlarr
      DB_SIZE: 5Gi
      # convention: DB LBs live at 10.69.1.5x
      DB_LB_IP: 10.69.1.57
  targetNamespace: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
