---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: split-pro
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: split-pro-secret
    template:
      data:
        DATABASE_URL: "postgresql://split-pro:{{ .db_password }}@split-pro-db-rw/split-pro"
        NEXTAUTH_SECRET: "{{ .nextauth_secret }}"
        OIDC_CLIENT_ID: "{{ .client_id }}"
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
        OIDC_WELL_KNOWN_URL: https://id.${DC_DOMAIN}/application/o/split-pro-oauth/.well-known/openid-configuration
        EMAIL_SERVER_USER: "{{ .mailgun_username }}"
        EMAIL_SERVER_PASSWORD: "{{ .mailgun_token }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: Postgres
        property: password
    - secretKey: nextauth_secret
      remoteRef:
        key: Split Pro
        property: nextauth-secret
    - secretKey: client_id
      remoteRef:
        key: Authentik OAuth
        property: split-pro-client-id
    - secretKey: client_secret
      remoteRef:
        key: Authentik OAuth
        property: split-pro-client-secret
    - secretKey: mailgun_username
      remoteRef:
        key: Mailgun
        property: username
    - secretKey: mailgun_token
      remoteRef:
        key: Mailgun
        property: smtp-token
