# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:FskE9p0Y+PCCESZtRLS9ujg9nQm5YDiVdGLkWvQCI5MDXB3vT/BJJMXe31ET,iv:azRwCVzebLAxPj7oOT+Q952zG7Ho0aKPH7t4733BPpw=,tag:hvcqSBGCrVTFwpwGwEhR5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYlV4YmtWRURmdGpUNFFh
            Yk4zT1NNKzZsRU5NQTBTZTRObmdTeGRmTUR3CmNkSnY3WHdLeEhZRlpTbkhxR1JY
            N1Y3Zk9rUkR0MkIrTXo2bW03cmNTV1kKLS0tIC9UZTUrU2x1WGgzdThOWTkyam56
            cVNjaEVrU0pENUV2UkRZOVZrR055RGsKJxC/nK9oCEGLlJtcUUb1dgb0JX9mjiJ6
            GDp8nbw2C9R+QIZvLnK9rFUi5uRrW3At8OXZKrK86kBEKyifpFk9NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR1JlQTdxV2k5OEtFbE9p
            WHlqdzZLVFIyeElmR2FGQUM5Zi8xUVNWM1RRCkd2ZjRoOXFKQWNudjVVbzIrQXJx
            OUIxRlUxUWxTODIzS2l2TzVseHlmZmsKLS0tIHNVaGxOUmdjcFhXR0w0NlU3RWZk
            cXpOWS9RM0tDeXBKUjA1OFJYVE1acFUKbOF67RI183dMP0/+1f0Q9Kr6/F6VKTcT
            BYa8NYGauwF5RmkX639zBXq9oPBNJd0QNKkdSfgXpKvhhUvc40wu7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZFZGRjRkenVxcWppYVJU
            cVF4bnJlczdvZktyV2F1WmVHbDJNRlVmYkF3CnpheTJaaHNadnNSVVNPUDRsR0ZD
            K3o1OXR2Mzd3VTZUbmtmUTZqbXVwNzQKLS0tIEZyZUpSdWRxRWRPV08rQnhlVm43
            aXlXVlh2VkdoMldqZ2FUMVRMSWhFTFUKeSuzVTjf0kOsjlHZaqhP7MlmyfwlBRvl
            gNsRqS2Ij9WmdIJb6/N68X2aGjeDo182z9zflDsNOAwsMB52jmPSCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWFNrRGdMU2tsVXBIZ0tP
            ZmJaTVpiejRnUnhDSXBQU0ZXMHczZWMzMFhjCnkrOTVyRWpSSEwwcHgyVFpLckdR
            TzgrL29Zb2xtS3h3VnVidkxxRXhjelkKLS0tIEtQdkR6aGdOL0U0a2FmbExpeXY0
            cGhwOEVrNFZ6bE5qWXp2Y0N6R2VwdHMK07fL2B3UMQbLPdCKSnllKU65t9GHJHgo
            C+Gd4dHG3D+l7qjH0bKoRNufb7LDyqEkaohHN0ab6SqJ7+JXGl7YzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T21:46:48Z"
    mac: ENC[AES256_GCM,data:1anVtf5f+Wb3TFKrLc65B7G0JhsZrvXBAVvwz9/9yzAk0NLgjyrrsHlAzxkcKUunXTwH8jwipIGq+qJCei1dtb93GkXVQ9yRdbKDVp2FNLVNBroL+bpI/UEWbo4Fff7cDDXq/MTxWoZG5X3NUArCrlRDBDCIYY6jKLIqcVouMc8=,iv:c5Mm54MWxv9lGrQoUFsrA9GOBq37qlwCb9WlgdACiaQ=,tag:HDahz4lHpGAXo5HLTzmsSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
