# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:FskE9p0Y+PCCESZtRLS9ujg9nQm5YDiVdGLkWvQCI5MDXB3vT/BJJMXe31ET,iv:azRwCVzebLAxPj7oOT+Q952zG7Ho0aKPH7t4733BPpw=,tag:hvcqSBGCrVTFwpwGwEhR5A==,type:str]
sops:
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVE52U1Qxb2phajVWQW1O
        cUNDQkVPWG5CbkZrR3VOOWRwUytzU2xrTlJBCisyaytUME9JMGMxMFFzMUhiRGYr
        TnRkdnFxZXhkUUdsaWZNbFFnV2hQdEkKLS0tIGpXbVdQdVhadnQ5T3RlRklwM3VU
        U2VpRE52S1NodWZiOUlJM2VEeE9EMVUKl7pLHfdRgwWwGN7jptWNbX6XrjuiKfAD
        F4Y3XBZ9h7WrWfG7jdljwZ8zGaUvIZI30e6Abe25dASJWeaazio5Fg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMEFhcXpiMForOGtUb2cx
        WG1QcGlDSEhRNWtva3dvYkg4eC9wTnFKNG1ZCmpVWlJjZFRoMUdwckhiVWJkei9M
        RWV1L2YvTnVkbHFaRXRpRk0vemJha1EKLS0tIG1obTBFaGo0SjdOWmNPOTI2NDF4
        MmFGSmZrY2FRS1Q0VVpNMXE0c2IrazQKw8UaJcBWFVmeObjT87zxSubVrL/x+i2d
        rSgU629igaT9HBImfGQN/1+1+7ARCX0YgQbXx9T8/UuquIBa1wTpRA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSjlFaHZiaE13Qm9GSW91
        VzVLS2RiQ0k2QmhTSTB4THRwclF3OUpDSlZNCmgyai9GbDFmd2tMc2l5UVV0SytK
        L1Y3OXIxd01FMEtPWWxFS0FLM3dkM1EKLS0tIFlYYzh5YVNvUURyM1ZLR0o3WmMw
        bEo3K0F2bWx4RlZUWDNkd3NSeXU4S0kKV8zZlbxescimh+wZNDYJXp+FrM0GoQPw
        bKmJhKgMOzWAPyZAnTQEHMF8AS8kk94eSdFM3Y/Nyq3jgdGsa0rBRQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSXJ5UVpMNnJqSVZ5MUZQ
        bk5DL0JhMkpDaEU4YU1ScXFWdVdDd2xXeXl3CnNlSEVjQVFFbUg1cFpvd2l3K0pq
        dTIrRm9DcFQ5eGltUWNMYzNqMExURjQKLS0tIDRTdXV5OXlKSlVzMm9rQ1Qzb0gx
        NXN0ckVFZGZLbEk4R09jdUdRQzVSZTgKZuj5PTJfPqDrsYOjbrlMvk6laqticXaO
        2gMlNuTjlqi1d2UnhKRJyuMu0zw5Zci+bIOFSBRNLuRrwPpJMB1e2w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V1o2dlFKUFRmcm0vZFQr
        dlcweUFKbkNtNjQrUi9aNVJ3bnJBb1JVYUQwClI2T3hvOXBONmxvdnQ3OUxzTkJ3
        Vkh4TkxCenlFd2dDVm1UQTJrbHdTbzAKLS0tIG5BSmxrRGhRNjdmWld1OE5IUjZw
        eDNXZ3JIWnhHZVBvYmFaSE1BMXdUZEUKQJPhrYiNGEJ7wW6QYNHOJiOsbN+F/BFs
        mmPmmlCe+/dlDxDozFVHiZ1zS+YdgcA5Nsjpk9ilwVRMDB+0+3mlyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T21:46:48Z"
  mac: ENC[AES256_GCM,data:1anVtf5f+Wb3TFKrLc65B7G0JhsZrvXBAVvwz9/9yzAk0NLgjyrrsHlAzxkcKUunXTwH8jwipIGq+qJCei1dtb93GkXVQ9yRdbKDVp2FNLVNBroL+bpI/UEWbo4Fff7cDDXq/MTxWoZG5X3NUArCrlRDBDCIYY6jKLIqcVouMc8=,iv:c5Mm54MWxv9lGrQoUFsrA9GOBq37qlwCb9WlgdACiaQ=,tag:HDahz4lHpGAXo5HLTzmsSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
