---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: cloudflare-secret
    template:
      data:
        CLOUDFLARE_DNS_TOKEN: "{{ .CLOUDFLARE_DNS_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudflare
