---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-localpv
spec:
  chartRef:
    kind: OCIRepository
    name: zfs-localpv
  interval: 1h
  values:
    zfsNode:
      encrKeysDir: /warp/k8s/keys

    zfs:
      bin: /run/current-system/sw/bin/zfs
