---
keys:
    - &john age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
    - &lab age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - &en-t65-1 age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
    - &da-vcx-1 age1h83ljrtj9c0m9mc43glt0jpz5kh6xnupuhv8vtekanvk97rflqcqu4d4j9
    - &da-vcx-2 age1h294f87wq8kfwrzkctx6v3qy9nc80jwrvm5v9rsgzkverpuqtppsl258c8
    - &install-iso age1fvv4l46j890x8387lly88n2aww4xdxma2jd0ta9zysf97hkvhg6smg6x0r

creation_rules:
    - path_regex: secrets/secrets.sops.yaml$
      key_groups:
          - age: [*john, *en-t65-1, *da-vcx-1, *da-vcx-2]

    - path_regex: secrets/da.sops.yaml$
      key_groups:
          - age: [*john, *da-vcx-1, *da-vcx-2]

    - path_regex: systems/aarch64-darwin/da-n1x/[^/]+.sops.(yaml|json|env|ini)$
      key_groups:
          - age: [*john]

    - path_regex: systems/x86_64-linux/da-vcx-1/[^/]+.sops.(yaml|json|env|ini)$
      key_groups:
          - age: [*john, *da-vcx-1]

    - path_regex: systems/x86_64-linux/da-vcx-2/[^/]+.sops.(yaml|json|env|ini)$
      key_groups:
          - age: [*john, *da-vcx-2]

    - path_regex: secrets/en.sops.yaml$
      key_groups:
          - age: [*john, *en-t65-1]

    - path_regex: systems/x86_64-linux/en-t65-1/[^/]+.sops.(yaml|json|env|ini)$
      key_groups:
          - age: [*john, *en-t65-1]

    - path_regex: systems/x86_64-install-iso/minimal/[^/]+.sops.(yaml|json|env|ini)$
      key_groups:
          - age: [*john, *install-iso]

    - path_regex: homes/[^/]+/john/[^/]+.sops.(yaml|json|env|ini)$
      key_groups:
          - age: [*john]

stores:
    yaml:
        indent: 2
