---
keys:
- &john age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
- &en-t65-1 age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
- &da-vcx-2 age1h294f87wq8kfwrzkctx6v3qy9nc80jwrvm5v9rsgzkverpuqtppsl258c8

creation_rules:
- path_regex: .+\.sops\.(yaml|env)$
  key_groups:
  - age:
    - *john
    - *en-t65-1
    - *da-vcx-2

stores:
  yaml:
    indent: 2
