---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
  data:
    - secretKey: secret_key
      remoteRef:
        key: &Authentik Authentik
        property: secret-key
    - secretKey: bootstrap_token
      remoteRef:
        key: *Authentik
        property: bootstrap-token
    - secretKey: tofu_token
      remoteRef:
        key: *Authentik
        property: tofu-token
    - secretKey: bootstrap_password_hash
      remoteRef:
        key: *Authentik
        property: admin-password-hash
    - secretKey: postgres_password
      remoteRef:
        key: Postgres
        property: password
    - secretKey: email_username
      remoteRef:
        key: &Mailgun Mailgun
        property: username
    - secretKey: email_password
      remoteRef:
        key: *Mailgun
        property: password
