---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oci-repository.yaml
  - ./external-secret.yaml
  - ./pvc.yaml
  - ./cron-job.yaml
  - ./helm-release.yaml
  - ./http-route.yaml

configMapGenerator:
  - name: authentik-blueprints
    files:
      - ./blueprints/tofu-service-account.yaml
    options:
      disableNameSuffixHash: true
