# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:IxP4OLbwjVDx3Fwl/venHc83bDHiAZeE7RYVhv6xpa2XtFfGGq7AHQ==,iv:IUDqjFs+7cFDIQE1YYzTwUyC10/k2RydPiOtg/XAq7w=,tag:ag5CPdF82aM0JFymYgOEVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMDlzRm1xcUx5ZW44NXpl
        OVNFUy8yZDJ4ZzdtM2c3S1dnakhhaVdPUDNBCmQ0UkZQdm9jV2lhZHhBTDFXU3JS
        amJPZnpjcENaU00wT3ZqNGkrVThkUEUKLS0tIGd1ck15RHorOEkyVWtWQzQwckc2
        T3dBUXIvZEEvTG4zSHpwcE9raGpSTU0KfMu9wQAPvP6LemdADOiNAkqP274lzRxU
        KEcz2fwNleBWQ49EmbeeOHeUe7z8QIp/py4IjCCAyPaaciAY9vUlfg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaGJreDRFYXZITmpWaDUx
        ZXpLRjVHSUN5MFJ5cXdUelZYeUoyRHhVWjM4CjZYTHhiVmdkU3IxQ0llcTFPNjla
        ZHgvSFFHUTc4RDhpMnQ3aXFXQVpZVmcKLS0tIEd6eVk5TGR6V29jNlVZODFvODdq
        MDE1R0lkdkxGSXczWktUSTk5NW9EUWcKtmoCd/cZoKtKYRVMWGXDQYU2LTXLhLi5
        Y3m6RIWyxcRIqbakF05TseChzk5ENtpCB7Vz51nHV+ZGYXd3ZZp6IQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT05BQU43YmpoTk1qS1FY
        OCtkd1hHR1FjWVB3RDJIQzRHR0p5U3BBTmpvCldjK005SE56NlpJT2xFd25zU1F0
        VVY0aUVIU2dPQkFSYW4zbkI1OXE4U1UKLS0tIGo0QnFuT3NPSjVLQXYwSzJ5WEJo
        dkRXclZXTlJpNGM2S1h0V2d6S0VUVEEKmXTDl0swbb2GshrmaM2SVwFLGuh/OjHD
        3/qsZZTXAwK9IDYBx7JELylBK3nxyAc714X6H+V+ZUipC1U5ojJcFQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5amZ3Nkx2ZHNSK3Z2dnN4
        bFZldzVLeDdvek1nWU1ISXlpRkpxSkVIZHcwCmZXRXZPSkp3am14UVcxc1h4eE5o
        YldNNExCaVNhQWJGcUtQS3NSVEUvR2sKLS0tIElzYmV5c3llZ3JYdDFqbnVLVTB5
        OWJzcUVFS0NtMFdZR1o4eTVCb3N4NlkKCHUEfnOG160DTuynenQmcyf+KE+Tknku
        +HeGOZXHw+/P6Nl83Vg0Kx2GS1Nhl7z/5UpxfmRUL3Lfq1LuAdPXvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:DwrpBJzaWOcs2VACs9iC6T+6E6kCAFZryCJYElJ1CwZ4q3ZM56z2Dk0OWqjjKjbqdmVg6jFSQu5h5I6whRVHb+WcWlOtjM/y8yAtVwwetDlsVeVCJlc52ZYxKz5ff5VXJ0zuEcj91bmbwSr22p2tBtKqi4sVhsZtpwmURTzAVvE=,iv:IUgnIHR+mRGAxqp2Zm5XYbGhMYMsMW+pVM3bb6kOcjY=,tag:GJW29TY2G0bV4X6FuDbACw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
