# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:IxP4OLbwjVDx3Fwl/venHc83bDHiAZeE7RYVhv6xpa2XtFfGGq7AHQ==,iv:IUDqjFs+7cFDIQE1YYzTwUyC10/k2RydPiOtg/XAq7w=,tag:ag5CPdF82aM0JFymYgOEVA==,type:str]
sops:
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bzZCNDByNlpzOVgwM3lZ
        YkpNR2Q2UGVzcEZNdHREaTdXZkl4SXRTK2drClhaTlR6RmxmSDJKc2pBaXppK2U3
        VjdNM0dEVkVGQjRJYVVlTGxlQXNMdVUKLS0tIGpENmQxbVBaUEVqS3BESlpqSVFk
        TjhkZ2o2ZVMvNEV4clFreGJ6ZFhZVWcK39deEkluUH1kPcAOg0FH86ADyD2WJXVp
        w/A7dRa1Bf7W7Fw0Akxp+BNYydabNsaBbDsZNVdblSo2x5MDWikAgQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETFpZTmc3MkJ6UUlNcGt4
        SDJBMWl5LzVZeXlpcjlhK0wzZmk5SFFMd1U0CmVjYjU0b3hhR3k3ZmJSdzlvNHIy
        OFg5dEhqbmxndWNpb3BvRWFkanBhd1EKLS0tIGxzOFhkZDIxY2hmQVRaaUNwVW5r
        RDA4b0EzY0Y2NmNkOHlwYWtXbmpXc0EKoW36ui4oY8HQdJNY6fyGx7xxTPCSgqqG
        9pK3db8TYRJqD/JEvbA029+Sttml9n1RrYHmxQf1Uss3sY1ma1nvNQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndnh2OFI4VzRESmh3L2xJ
        bHNRVjVZdWFUam1xdm9KSmVqRXdxejY5SjBFCjdhSVZ3aTYzWU04RlMzSjZRUVY2
        SUZabjRuUmtsaVFYTGZFUmtablhpTDQKLS0tIGVuRWt3MGJrSTg1bUZQNjlvb3BU
        bXA1YVF4aE5oUC9Zd1NFOWt5dU1QQlEK5nDF39eaOQPZHgeuZBBk53VIWClJoLgy
        7Z0y28esHFDYR2oC+h/5OBF65fj+gg10RFuEOIkEoRkyVLQFQwFE6g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVWZYdFlLVzZkS1dZYVU3
        RWdDYW5Oa2xMLzhyUEx4dnA1eVhkMnNQZm1FCmlnd2tBRTBZcEpvVjluWVA1SVFx
        TEpDbXo5VFBROE9TdHBjdG5UYm53VGsKLS0tIDN5aElKSnBkM250NTBwaXlyWVND
        bzJlRnJveWQvOFo3dU92RGd2aVh2LzgKKZONa9VVa/lRiR2cL3Z/u5WhX0/KC9D5
        4kw4uuCO+j0y9qxfJLIJi9DIavKAXQzePMRxIJS1ASmB5b+q1XqH8Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZFp5a0haZ1l2eldBc0g0
        aE1nUzM3WnU2aUR3YXNKM2tqUnJWMlhaank4CkFKNlJKcElPNTArZ3JYdmtFMC81
        dW90am1sV3lyazBwenFVQ01LZDBic28KLS0tIGxUVW9OK0JLbmFiUHRmYVF2YmdS
        a3k4OEYzTHZ2SWk4WFMxelBCb2loMlkKWiGmx7Y6UoKMe9iLam80VIbiFBsw9QXu
        yHWgb2aA3mQu/W9C15s3DmKePmTXc71j9HWyTEHHIim8Z84WZnGo0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:DwrpBJzaWOcs2VACs9iC6T+6E6kCAFZryCJYElJ1CwZ4q3ZM56z2Dk0OWqjjKjbqdmVg6jFSQu5h5I6whRVHb+WcWlOtjM/y8yAtVwwetDlsVeVCJlc52ZYxKz5ff5VXJ0zuEcj91bmbwSr22p2tBtKqi4sVhsZtpwmURTzAVvE=,iv:IUgnIHR+mRGAxqp2Zm5XYbGhMYMsMW+pVM3bb6kOcjY=,tag:GJW29TY2G0bV4X6FuDbACw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
