---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./namespace.yaml
  - ./home-assistant/home-assistant-db.ks.yaml
  - ./home-assistant/home-assistant.ks.yaml
  - ./homebox/homebox-db.ks.yaml
  - ./homebox/homebox.ks.yaml
  - ./hubitat/hubitat.ks.yaml
