default_config:

auth_oidc:
  client_id: !env_var HASS_OIDC_CLIENT_ID
  client_secret: !env_var HASS_OIDC_CLIENT_SECRET
  discovery_url: https://id.${DC_DOMAIN}/application/o/home-assistant-oauth/.well-known/openid-configuration
  features:
    automatic_user_linking: true

homeassistant:
  name: Home
  unit_system: us_customary
  time_zone: America/New_York
  internal_url: https://home.${DC_DOMAIN}
  external_url: https://home.${DC_DOMAIN}

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

recorder:
  db_url: !env_var HASS_RECORDER_DB_URL

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
