---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name home-assistant-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: *name
    template:
      data:
        # consumed by `!env_var` in configuration.yaml (recorder)
        HASS_RECORDER_DB_URL: "postgresql://hass:{{ .password }}@hass-db-rw/hass"
  data:
    - secretKey: password
      remoteRef:
        key: Postgres
        property: password
