---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name home-assistant-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: *name
    template:
      data:
        HASS_RECORDER_DB_URL: "postgresql://hass:{{ .password }}@hass-db-rw/hass"
        HASS_OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        HASS_OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
  data:
    - secretKey: password
      remoteRef:
        key: Postgres
        property: password
    - secretKey: oidc_client_id
      remoteRef:
        key: Authentik OAuth
        property: home-assistant-client-id
    - secretKey: oidc_client_secret
      remoteRef:
        key: Authentik OAuth
        property: home-assistant-client-secret
