---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oci-repository.yaml
  - ./external-secret.yaml
  - ./pvc.yaml
  - ./helm-release.yaml

configMapGenerator:
  - name: home-assistant-configuration
    files:
      - ./config/configuration.yaml
    options:
      disableNameSuffixHash: true
