---
autoDirectNodeRoutes: true
bpf:
  masquerade: true
  datapathMode: netkit
bgpControlPlane:
  enabled: true
cni:
  # Required for pairing with Multus CNI
  exclusive: false
# NOTE: devices might need to be set if you have more than one active NIC on your hosts
devices: enp+ !tailscale
dashboards:
  enabled: true
endpointRoutes:
  enabled: true
envoy:
  rollOutPods: true
  prometheus:
    serviceMonitor:
      enabled: true
gatewayAPI:
  enabled: true
  enableAlpn: true
  xffNumTrustedHops: 1
hubble:
  enabled: false
ipv4NativeRoutingCIDR: "10.69.0.0/16"
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: "dsr"
localRedirectPolicy: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  # TODO scale up once more nodes are present!
  replicas: 1
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: native
# https://github.com/cilium/cilium/issues/21603#issuecomment-1453753820
ipam:
  mode: "kubernetes"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.69.0.0/16"]
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
      - BPF
      - PERFMON
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: 127.0.0.1
# NOTE Can't use `7445` b/c this isn't running on Talos with KubePrism
k8sServicePort: 6443
# Enable bandwidth manager for better performance
bandwidthManager:
  enabled: true
  bbr: true
enableIPv4BIGTCP: true
bpfClockProbe: true
tolerations:
  - operator: Exists
