# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:b/8YAy2OXeXkU0lapqnqP9qfxWrDCKmbZnmezTX8SjQ=,iv:iNvxLevRxjbFtVTUAjzKAeqdRbVAYYqvDb1AY/x8wRc=,tag:Fz38f4nvzZfLqgiyTUAbxw==,type:str]
sops:
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQjVWZUh6ZytMbGtENWFF
        MFQ2cUFoMmhhUHh4L0dnTHRkWlVYeWdMbkQ0CnhYOGxWRVdTeGp0RVhUa3N1c1M2
        U1ZmeU1SRFAyZkIvcStnUGlObXFqQmcKLS0tIDdPZGU0UzhPcVplK2g2Tm9WRDMz
        Zy9vOEp4M0NKT3c5V1l3Qlg5QXlMREEKkhlMEZ4rWxIE03XWQDA4NIL45RFc1hsY
        1X+yOvIYY4nOHKcqcXkZfN7VB8YLWlGmnZw0kxYDAA03UsA8A5qSXA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb04rTFQxK1BJVEJSSjRw
        V0xIOExyRnV2d1NWZ3BGSUlQVFVHV3VsQTMwClp3UHhxR2pmSW0wYjRwTnlZTDZk
        eDZEK3NTYjRBWlpBMFYzQTlXTytrbVUKLS0tIGVLellsaEg0ai9pSUFpdE9XbFFZ
        eGdJaGdYb1NUei90VXlBblFKNVFocWMKnvLTKgWCudLPfTRenDwjx23Q46XrQQgY
        RY+E9shWtvLlpLGLRCZKU/S7ZEVAMNGyLC5c+pkgK/laaMLHozA46g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTEtzRS83bDVEZWozQXRC
        UUUyNzcvMURBYXladHZ6ZVBybE8xOWZ4aHcwCjdvTUVsa0p0TTMxYlMySzhRVHpS
        d1NYZGN6c01HZy9CZkVnUEFHSWQvTFUKLS0tIDVwTC9kWDdqVVRJTEIxbnpnMUZH
        dytBbzI3TTJXdmFsN2hCK001b2RPZEEKD8QunbKgtDGMg/aIZ+taAemO76p88cTk
        Lk3Jc/IFkPxLmYmH4vODKQwVvVqbEsXlCMI8ICfc3hInBdA/M6i0/Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVTROdHBsR1cwT2lWY2dl
        eEUxVW8rUUtERzBKajVpdjNSRGFTdmVoVEI0Cm84T1FDdFpVSkNySVg1ZGc0Q25u
        RXJPQkhMTzBOS0NNVnlMSGZsWGlhclkKLS0tIDY0M3lKZ1VQRXBNbit2TlZvYnRs
        Y3Q2RjlDQXpmZFhvSG9PNDhXZFZiUVEKmejBW4ccdusDC8o1XnZlw+++wgWqVTXo
        apcKu316gAQvEXYXqGRnkA6GRGFvdQ+kFl0URSPr+A2+0Rfl9ArD6Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbFI1TVYxTzhOZldJdzRR
        RzhRTDIrLzFPWGVLVVN5WHJOZVVyaGU2UVNvCjhmRFdTN0FuazdVeit0YWF5Y2dO
        dVVUU2kxbEpsUHVHYnBWbGNyQTJ0cU0KLS0tIFhkWjF4bmEydVREOXRYZGxQNjFG
        S1FjK0RFWkk5ZENTaGZLRmhpcHIzM3MKQoeFXZYvdg+wq9aPfFMUksrh2/28u7+r
        Cejcut9KTZtiw5En4oZERxIB+vXI91T953KIXeMTNRstdfZXp0y5Ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:VGnLaCpDejw51JJ3gsitCpUAjBCYAUfMf+qqHDds7aVnRZZJa49apdYnGOt6ZXIYcvli1ZvTktRnEvES9GE2F/4MtZq6rdPo+gYwkLyNokexRdC4VcxogE72iZRFFHmPO1tvCd14IMTIkDinVhIpJDGGyZIhFykCEQsxVv6AfdI=,iv:4FYinBjSHPJu1eF9kPXNyaT1JGjJ9U8k0xWz+l6ShkM=,tag:WUBzvQtumgWemaiNgjHNlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
