# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:b/8YAy2OXeXkU0lapqnqP9qfxWrDCKmbZnmezTX8SjQ=,iv:iNvxLevRxjbFtVTUAjzKAeqdRbVAYYqvDb1AY/x8wRc=,tag:Fz38f4nvzZfLqgiyTUAbxw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbU1ON0hhNjQ0SHJ6THBW
        eEFvZUdmYVhwbFA5bnU4SHFrUUtYNkVaN1FjClE3aEFOQUxEVmlYRHZGOExiM2dK
        ZXlqdzkzTFhML2V1cVZtaENqYnhiQVkKLS0tIElSMGtVWWdJN25xQkQwZGlkM0E0
        ajY4QTI0S2h3a3VYeUU4T1Bxa0hqSHMKmzSFlQ7nIGsh6hqMQ+mGRj7Y6c4HU82s
        QadK7VpSfJbISNMmmyB1CNlmjSP7PfGBFQ7RDJSjoP7nChpFdWuB/A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMjFlTUR6QnJLcVBhRy9H
        L0lQRmdEQlljODlmNUtVQzVLVkxHSHVUUzFBCkxXZVprdGp2ZklXeW9mTmpnbGxZ
        dE9LRnRKWGx5NlJJeDBBdW9XaFFWNm8KLS0tIEg4VUZpd1U0QzdvRm9qbmVjcXVl
        RmJ3WGlXRlVIMU45cWZXMTZCbm9GYlEKmSdvBy4CQPjUeouK//JUZs83n5eaRU6h
        gm9AwhXpymXL2glCUKdO5obFLIXqSxPuS3mctBisvT8Y4X1FdX0+jA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ3BIcS9Qc1BCa01icW5r
        R25Oc2pBeHdWUkFFQkxMR1lCZkFhOXpFRlFjCkNHdG90bC9QM21XYXUxOXpYYytZ
        ODdURlhYMkxhTkg5OUNLZHBFVW1xdWMKLS0tIDJZV0szL2J3MDJJV1NNcGF0czVK
        eC90MXdxYnFXQmk5VWpNd3BmMmN4OUUKYXvSgxrvsDPam6YqVX//MNpaZUXIRDuJ
        cdbHbT5RAPyd+U5XsVKYv3WP9UzKogvK+0CcWFZGW0HvMD9I72u20A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVY5WEJrSE9qVjM2NHVP
        Z0grdXQ4cTJobW1sSU5GNjh5M3dlYzVraEhJCjNoQ09EdXJ2SWJYTGZOam9aemc1
        TFJ0eFZ0L3QraHBqUUI3NHhZVGtFNG8KLS0tIDZPQit0cjRsY1VmTWJrdjVXY2tH
        M0hMb0RxRFZXR0krRnRBL0I4VTBpQm8KVv5FE1a6WvsfnH8SiIqZEW/6wz+nYSyS
        XL9am8UO3z/hY7MrlGNk1ojkYgL5TJbcN7UByc739uU7u6K/PRf0Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:VGnLaCpDejw51JJ3gsitCpUAjBCYAUfMf+qqHDds7aVnRZZJa49apdYnGOt6ZXIYcvli1ZvTktRnEvES9GE2F/4MtZq6rdPo+gYwkLyNokexRdC4VcxogE72iZRFFHmPO1tvCd14IMTIkDinVhIpJDGGyZIhFykCEQsxVv6AfdI=,iv:4FYinBjSHPJu1eF9kPXNyaT1JGjJ9U8k0xWz+l6ShkM=,tag:WUBzvQtumgWemaiNgjHNlQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
