"""Create or update ``rbn`` drivers on the hub from their committed bundles, idempotently.

A driver is matched by ``(name, namespace)`` from the hub's user driver list; the
namespace is read from the source and must be ``rbn``, so code in any other namespace is
never touched even when the name collides. An existing driver is updated only when the
hub's current source differs from the bundle, with the ``version`` read moments before.
"""

from __future__ import annotations

import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import hubitat

from . import bundle as bundling
from . import manifest as manifests
from .hub import Hub, HubDriver, HubError

NAMESPACE = "rbn"
PROBE_NAME = "rbn include-all probe"
LINE_NUMBER = re.compile(r"\bline (\d+)\b")
Kind = Literal["created", "updated", "unchanged"]


class PushError(Exception):
    """A source that cannot be pushed as it stands."""


class ProbeError(Exception):
    """The include-all probe failed to compile on the hub (message carries the hub's text)."""


@dataclass(frozen=True)
class Action:
    source: Path
    name: str
    kind: Kind
    text: str
    existing: HubDriver | None = None
    version: object = None

    def describe(self, *, dry_run: bool) -> str:
        verb = {"created": "create", "updated": "update", "unchanged": "unchanged"}[
            self.kind
        ]
        if self.kind == "unchanged":
            return f"unchanged  {self.name}"
        if dry_run:
            return f"would {verb}  {self.name}"
        return f"{self.kind}  {self.name}"


def _normalise(text: str) -> str:
    return text.replace("\r\n", "\n").rstrip("\n")


def _same(hub_source: str, bundled: str) -> bool:
    return _normalise(hub_source) == _normalise(bundled)


def plan(hub: Hub, sources: list[Path]) -> list[Action]:
    on_hub = {(driver.name, driver.namespace): driver for driver in hub.drivers()}
    actions: list[Action] = []
    for source in sources:
        identity = manifests.driver_identity(source)
        if identity.namespace != NAMESPACE:
            raise PushError(
                f"{source}: namespace {identity.namespace!r} is not {NAMESPACE!r}"
            )
        if bundling.is_stale(source):
            raise PushError(f"{source}: bundle is stale; run `bundle` first")
        text = bundling.bundle_path(source).read_text(encoding="utf-8")
        existing = on_hub.get((identity.name, NAMESPACE))
        if existing is None:
            actions.append(Action(source, identity.name, "created", text))
            continue
        code = hub.driver_code(existing.id)
        kind: Kind = "unchanged" if _same(code.source, text) else "updated"
        actions.append(
            Action(source, identity.name, kind, text, existing, code.version)
        )
    return actions


def apply(hub: Hub, actions: list[Action]) -> list[int]:
    """Perform the writes; returns the hub id of every driver the actions refer to."""
    ids: list[int] = []
    for action in actions:
        if action.kind == "created":
            ids.append(hub.create_driver(action.text))
        else:
            assert action.existing is not None
            ids.append(action.existing.id)
            if action.kind == "updated":
                hub.update_driver(action.existing.id, action.version, action.text)
    return ids


def library_names() -> list[str]:
    return sorted(path.stem for path in hubitat.LIBRARIES.glob("*.groovy"))


def probe_source(names: list[str]) -> str:
    """A driver that does nothing but include every library, so the hub compiles them all."""
    lines = [
        "/* Generated by `hubitat probe`; pushed to the hub and deleted, never committed. */",
        "import groovy.transform.Field",
        "",
        'static String version() { "0.0.0" }',
        'static String timeStamp() {"1970/01/01 12:00 AM"}',
        "",
        'deviceType = "Probe"',
        '@Field static final String DEVICE_TYPE = "Probe"',
        "",
        "metadata {",
        f"    definition(name: '{PROBE_NAME}', namespace: '{NAMESPACE}', author: 'probe') {{",
        "        capability 'Sensor'",
        "    }",
        "}",
        "",
        *(f"#include {NAMESPACE}.{name}" for name in names),
    ]
    return "\n".join(lines) + "\n"


def resolve_error(message: str, bundled: str) -> str:
    """Append ``<library>.groovy:<line>`` for every bundle line number the hub mentions."""
    resolved = []
    for match in LINE_NUMBER.finditer(message):
        hit = bundling.resolve_line(bundled, int(match.group(1)))
        if hit:
            resolved.append(f"{hit[0]}.groovy:{hit[1]}")
    if not resolved:
        return message
    return f"{message}\n  -> {', '.join(dict.fromkeys(resolved))}"


def probe(hub: Hub) -> list[str]:
    """Compile every library on the hub via a throwaway driver; returns the library names."""
    names = library_names()
    if not names:
        raise ProbeError(f"no libraries under {hubitat.LIBRARIES}")
    with tempfile.TemporaryDirectory(prefix="hubitat-probe-") as tmp:
        source = Path(tmp) / "probe" / "probe.groovy"
        source.parent.mkdir()
        source.write_text(probe_source(names), encoding="utf-8")
        bundled = bundling.write(source).read_text(encoding="utf-8")
        ids: list[int] = []
        try:
            ids = apply(hub, plan(hub, [source]))
        except HubError as error:
            raise ProbeError(resolve_error(str(error), bundled)) from error
        finally:
            _delete_probes(hub, ids)
    return names


def _delete_probes(hub: Hub, ids: list[int]) -> None:
    """Delete the probe by the ids we touched, then by name for any earlier run's leftovers."""
    for id in ids:
        hub.delete_driver(id)
    for driver in hub.drivers():
        if driver.name == PROBE_NAME and driver.namespace == NAMESPACE:
            hub.delete_driver(driver.id)
