---
originRequest:
  originServerName: "external.${TLD}"

ingress:
  - hostname: "${TLD}"
    service: &svc https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.${TLD}"
    service: *svc
  - service: http_status:404
