---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proton-vpn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: proton-vpn
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Proton VPN
        property: private-key
