apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials
  namespace: external-secrets
type: Opaque
data:
  1password-credentials.json: ENC[AES256_GCM,data:wokY1xOX6ne/OEk4DmsVc1yOdUCfJZnu/w0aFJuNrydz8hN62krLEW9LC0gfX/srKApUDOEjpvsb9vTk1EJZEgjWdGUvXMfOt+jLnpQMrV/qtqnWxvtTzJs8gH2A1eXIvDNn+3jXrpSAVpLvyX6irQKMYDmNCi4JaxZt2ffoml/gXGi07tKwQ8YOJfsUIV+xgCJK3FSdm0tisw09Dcajxlz9s+DxRvDPSEW8ZHGpOQCm1u1LE1kkqGGM+GUmaoMXoPN9liaY4y+u29UvwcbNh7MMstmjo45G/QiOEtvNgBjteK7MQMADE18YI+RhG4/+KCLUWRDUbUwyAiumKRq8/T992b7yX2By3VuOJ3ZkynAWlunK8Qkainw0TT137oFXM4o9kB8dlJQ143v3pmq6DN+cr52eYofGQGwzyrjPr8Ns4Jyv5vsaReD8rPRT0gbx/IsyVgYqLGr5Acn+8MT6S4w8mnauCrcpN7+a2MSDuah9VmgzKPtaN51VqVJ05NSZjlRE1frMbPjBQmD3Vk9nuDwz/gOc7L11pn8xI+xPU/1s8FycamILCIAAb8LmOqMor6+pW0a28DO2p55CG7Kqp1vaqyC/JsVvtGziu6mOH/bwLcYvjDuXXORyGYVR4TO8+kkCziTTNOYIl/d3mjbXYl0m+AncI/ksCgf4P0aRAzPwJYJ5mIe+x5EKLHu/IuovMvUim17QCcgXM6XwE6dNF6Ala5dqKKLqn0gAoiivtSj8+i3HS5xTI0KrZ8z2OPeoa5vLxii6hhmlPUBJc3MAMklryaGxsBNQh6yJWvyV7K6Y7WsjQr4KXP2cykdo3jqSpI35nI2t8q/iVb8oLk8rojzW7mjkN904wBmRL4nH7EHDTahTNoVyrmWZSsbGMu1ZDIkKjqi3Lf4d8ph3bIYLyP6/COWwXEZQUha69tgn62Sab+sjlKcOG0Vb6CjX6g0DRgN6S4dhTr+fan+QRDi06cRHDWZDeY7pmvOn0/RKx+mvv+jJm2Vc8NBJCtrCVhJect7fKecJcS+dcDqOPkQ2ZKMPbIWwHQ7XlnwwSVYke/t6u7XsByCMJMi7Sdzj1cOGFXUoclp9k6CKeY8OyspZxGbOw0z3py1KV9p0KpxJmXddxIs0jQjyBikoerdNxXknCO8gBVCuIEiWPl/4CJWBjLEHhRh9Q+rbuomdN1FHrnHJupuoIiC9z8AufsgT+/O/A1KQzELrxSWG18BbHhHIjbGQBDEA3uaZKJfbXnjj6AC9W2HA5yZIDhYuvHLL/9p4/v31ZZy9rcILjnVKlGRoI4LF4fDLNifiloDntL8EsqmNdweX7slhphJHmNa0p0+fBAdxgGA7q3iX57Ir0Dh4UZpVWwaU4dsY8z0Ta/2BAobwMsIZ/zxVtkHiePbVTbMrxq/oAdG60KbyuaPyPr/Rwck9fyfxugZbBoE/Sg1fW+38TROtxegZ5YjpT04iYcI7CK48/6GRsXE9Khya3EOHrtkHvrmqWSaczwpDUBQMnaXLyMBJWtJi/coeoVKa6Mwv8XQLCQXb0zCzmWK0vIIA+khTjmp5Qqhttqzctrt+vdUyLvMi387q720vzOGQM6wMAYVFw89GncL8xzW4a+Qi6LJW4bZWsFtDmHM/o96LrO1AJXP+eDugmuISA7W66MXQPSQW6EJ5djlQvKPRiJLWba0krHeCv0AWQYRjBgLA5qEmJApmzJULK18dwUQ5VpGMbRE960B9EEeBl/sPfyNFtkOOtlGIzSp8Ju0bmyxKPC1y7cCiFAb/hemRIoAqGJNINCLsy4V9OtXJWlpJsm+A6uEIpVy28mYgWOeIVeAGQbM7Dy5Im4WQ4G8YwK0HgH+PULlEzBQak4oEmshhWv+v+ckoT+a/PugriNXl3lZk8EUYQHNhtOtAIM2Bk2s6tBdQliM/Fi6F85Em+60rY2csRshe4x8nc9KUmV5esmRlvfZNYLaP0epEdH1o9zktH3PlQ+JLV7ibY7ZVuRAmnFFdPMniqGkLH4hzHI/mwpHsbSIYXbFL89FoWZSBP3euBcrf9Ir5X8tGHtQ32sdj9Zuz05C4NIYtoveG+w/dWGMOYEiyVbxFP7BdQYlnrX8k1uHC1m9GP8279qaGfYEvT9H63Rm9XRNlzrFo,iv:NdMgg9Mt//s7dORliZU010ADBQOflN4sRgqLstiHh/A=,tag:VCqsxS9dbO4cm71I1ROF9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bDFTTnNIUllvbFQyODZ4
        bWZ4R0oxeG9SeFcyMTlCU1EyQXRsdWNzd1NjClAydU1xTWZ6UGg1d1o1RmJjNUtS
        WkVUZ1g0c0tpWksyMkpydENNcEo0Tk0KLS0tIEhlTWtJUVd2Z3hFSDVIbnl5bGNO
        akNTbTlNSkZJWkpVSG5DWEhWdWhRVVEKLuh5hDikXRE6GQtSmcoIEZwAQVayRVCw
        wkPAHeDpTW/8zUearPs6egUm0dXFqsAoFFCjkKHG2MmOF/THL/kZjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8qp0vlv4myatfd0fnm0a2tayu3pf0se4rymmegjrg0sgtucnqeqr66l0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdE1XME5mUjh0VU1jSHJP
        VFVTQnFqL2YzZXlDOWVUWEVtTVFCM091SVVNCkRsQ3A0RUMvMnIxL1dnOTFIUnVZ
        TnpHMkZGSmxYcWFZV1NwT2xSQzVZdEUKLS0tIENwOCtVaVJsSlVYSU5rdFFqQWZL
        aG5uKzE5REt6eldKZFZiZ3Z3dm50dUEK5dRDBn8BhfrQKl1K7xt3b4ZJ6P/kp3Db
        6n5+opYTbsi1NvdPPgdlXlzFg95LzK3EWspdC3vVWzrMVZzxoKZ+Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTWcrc0t3Ynl6V2xEbGdw
        MW1GSFk2b2F4NjNsZUJtWjZpbVRzUEc4cWlzClRFVGdxOHdCcDZENXZFNDNrU1o5
        aDRHZDh0SDE4aXZvTTFUdkZ0Z1MzZ2cKLS0tIHFSdldJcnEvUkpKSVhIdXZ2M0ww
        SlZsTmg4NTZtRUNLbkJZOXRLSG5TQmMKz8WxR438Xor4/QZu/UUYdCtOPU25G0m6
        bl6h0ZvmExYpXFN/GNpJxQbF7e/xiw3Zdb50gaf6tZTR7JB1b0fx4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lklatlu5ce38ra73u3d4el079xh8ltnphkws22xhnr3sgf4mnujsgv7jgv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T13:16:08Z"
  mac: ENC[AES256_GCM,data:/rY5fuL3M3Gwnet4NGusXB+N/81e94Qf+0bISziHyuJopFRGDZ9Zn/2aPgCyPuJLv4Sgaqk7MxTh4QcAFT8z0dytrfdny8XpPyryOXrC82bYcIhXDryKugpiXLtnWNM0N7N7NrDI2ZrTH+yC4XEQeCwV5WNZqk7+Wen17GrOBYA=,iv:sSmvATYQJU6umEw3BMMzLYnmd2WHTTHmM0d2J8Y3JNA=,tag:gqWV7vNQWJPjigcA6RDqqQ==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: op-connect-ro
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:RvoIYaYa82ruFJXM8IZRhV7bxI7vsH9+H11CnkRkqsOo488MefZmccwZrlSCo0jRXVeKs45MgzznhKMkqTfQSrYGxYi391UdL1xvoiMfWCZpLxh41rTMr2Fqp40RKTpUcNhGG+sKHWd8AT4N3YHEd6HpoxtZAT0fdsU841onPHsZ8fAm1xbaInC0ti4ZBYkjnL13pAjO0Ltfx3G4QPwqKak0W5tzigF2jKi3+TkJ1Gub30P3f9oDzC6bIgAnPHOMAGwJPJvTBxCJkIQzq/XLPrmqYbRyS1nT+DbO6gZPvD8E7DcyHmlqMXZUkiJoTvnULdulYFyTkuAYS4RtYcEapPaq/dUyNpv6tIwKN7WnXdMGjIDXAnV55mjof/+EyPiPfvaH1NAvEgvrWEpDj6gWyd1a3Me4v+evXgs+Ick25/vQptxOpz1wNxakDx+jqcXnKcQsklgll5mMmQ39ppArpN6/ODCQi/j9ji1yNY/jIACGH/4jLEE+xzHRg8Ux+kSKVbRxQp/JNVxcDcsciulHZbVjn7bk8/BfZHnZw6zG2aE4hSVA4WlYoYuFqUSpHg4o3pYoUWlCbPcGSVcpM//CbUdNx8Pgix9xO2iLlEmg/yGoAYSQGyov6mRhPEpzpsVFhquLcm43ciZFRZoOcKpXu9M3BuhvbvTQ0pZpg+gs3tvN4sC2z09evmSczcsIxtjGPqoIrCdaefc+NYFHemeirJODafOOXTTcxouhA1wVsUFXj0VS0BvhQoQn4SGLBGzndDyN5koWJCHAbAOs94a04Ht+nvIvcdyFP+/s2Ftq9FtozWEiA22Ra7FaiA+n2YTKP4W1hkuxjTEiB+91JTxkL6Oy,iv:RVlUCGgICPWuVIj1k9ThRcXJHq5WVUkPpaWri4oLfco=,tag:4kF3+c8PQJCs30/q3iRZ6g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bDFTTnNIUllvbFQyODZ4
        bWZ4R0oxeG9SeFcyMTlCU1EyQXRsdWNzd1NjClAydU1xTWZ6UGg1d1o1RmJjNUtS
        WkVUZ1g0c0tpWksyMkpydENNcEo0Tk0KLS0tIEhlTWtJUVd2Z3hFSDVIbnl5bGNO
        akNTbTlNSkZJWkpVSG5DWEhWdWhRVVEKLuh5hDikXRE6GQtSmcoIEZwAQVayRVCw
        wkPAHeDpTW/8zUearPs6egUm0dXFqsAoFFCjkKHG2MmOF/THL/kZjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8qp0vlv4myatfd0fnm0a2tayu3pf0se4rymmegjrg0sgtucnqeqr66l0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdE1XME5mUjh0VU1jSHJP
        VFVTQnFqL2YzZXlDOWVUWEVtTVFCM091SVVNCkRsQ3A0RUMvMnIxL1dnOTFIUnVZ
        TnpHMkZGSmxYcWFZV1NwT2xSQzVZdEUKLS0tIENwOCtVaVJsSlVYSU5rdFFqQWZL
        aG5uKzE5REt6eldKZFZiZ3Z3dm50dUEK5dRDBn8BhfrQKl1K7xt3b4ZJ6P/kp3Db
        6n5+opYTbsi1NvdPPgdlXlzFg95LzK3EWspdC3vVWzrMVZzxoKZ+Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTWcrc0t3Ynl6V2xEbGdw
        MW1GSFk2b2F4NjNsZUJtWjZpbVRzUEc4cWlzClRFVGdxOHdCcDZENXZFNDNrU1o5
        aDRHZDh0SDE4aXZvTTFUdkZ0Z1MzZ2cKLS0tIHFSdldJcnEvUkpKSVhIdXZ2M0ww
        SlZsTmg4NTZtRUNLbkJZOXRLSG5TQmMKz8WxR438Xor4/QZu/UUYdCtOPU25G0m6
        bl6h0ZvmExYpXFN/GNpJxQbF7e/xiw3Zdb50gaf6tZTR7JB1b0fx4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lklatlu5ce38ra73u3d4el079xh8ltnphkws22xhnr3sgf4mnujsgv7jgv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T13:16:08Z"
  mac: ENC[AES256_GCM,data:/rY5fuL3M3Gwnet4NGusXB+N/81e94Qf+0bISziHyuJopFRGDZ9Zn/2aPgCyPuJLv4Sgaqk7MxTh4QcAFT8z0dytrfdny8XpPyryOXrC82bYcIhXDryKugpiXLtnWNM0N7N7NrDI2ZrTH+yC4XEQeCwV5WNZqk7+Wen17GrOBYA=,iv:sSmvATYQJU6umEw3BMMzLYnmd2WHTTHmM0d2J8Y3JNA=,tag:gqWV7vNQWJPjigcA6RDqqQ==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: op-connect-rw
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:aW/KnQ6voiuv9VU3kE0KlfOt8JKB1SmzO2vfZYdO6oh/c1F8wFACay1oz19MWPiPk39wM0rbWyFfgvkJXoB91FDzQr8KL01sQbPwhzWgn4JY2QrvCzEDvADF5SawTan4gN5BisQbi+2Na8RC5RmOqZ33rmiKsH4W6iGs4Di2G/8TQODAa8so2V3PLpfcKpX/yLnj637X/1qM/V1R5h7aA6mEoALqhZRpBfJaPYHtmjcXDbLOH8+1P0W77kn2kzck2wfJcBnYOB5MML9AiOlV/96UVnzLOVdTuvLsvVADceygpMWJ59KK4F21nEu+MKfXYoL/qbD0nCW53Cl3/t346VBDZzwKw/3n/i4DEEGhFM7nnrO5yW3p+QoBVzmN9zTawLi+UknSgxq1Qf95gYWS5wwtuYVzEkTSDSqnIIi+NsA7lI7z76icjKiY0ON/Wv64WSQNkJ+A1d+B6nIwF1c4gRud/UkH+m19Hx8Dkw+asi8SJHN6hoCgg6wdA+qdh8uuvcomq0LnEY+bUz55nDvs3XIWPUWSka3+UV+nVnIy10OctvlsMQkgJBGCR7WkCuqy0n5FZEHtAwfdwsWx0K671ACgSTKqAy0qrPlJ/+4OHHwZtC4ylrTC8Jn5xE8km2XpeX2s+ll0k3QBJGs3wh06vWiKT9qph6t0PBNNElxbhLsgNaBkDbYZ9nAWmuJX8tmIvjpzbFChp2TUGel4JKHWD2o1Q/Ockdemqf5CDCEWF0B+Oub+lCoj1PEGpmYZVF5K4PKNFLxRfLmyhLyyPEpHibrmjbmGrYdj7+rY2yN9MrGywDJU2mwDR76YDnletIsJl3uroNRPV+NgONIMi9nzYxikPA==,iv:EecUuj8Y0ZckSPZel0vthPrFJocI86eTb/Fy0YNCNQQ=,tag:mdoD4TyCWDXqxZTk4qtpMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bDFTTnNIUllvbFQyODZ4
        bWZ4R0oxeG9SeFcyMTlCU1EyQXRsdWNzd1NjClAydU1xTWZ6UGg1d1o1RmJjNUtS
        WkVUZ1g0c0tpWksyMkpydENNcEo0Tk0KLS0tIEhlTWtJUVd2Z3hFSDVIbnl5bGNO
        akNTbTlNSkZJWkpVSG5DWEhWdWhRVVEKLuh5hDikXRE6GQtSmcoIEZwAQVayRVCw
        wkPAHeDpTW/8zUearPs6egUm0dXFqsAoFFCjkKHG2MmOF/THL/kZjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8qp0vlv4myatfd0fnm0a2tayu3pf0se4rymmegjrg0sgtucnqeqr66l0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdE1XME5mUjh0VU1jSHJP
        VFVTQnFqL2YzZXlDOWVUWEVtTVFCM091SVVNCkRsQ3A0RUMvMnIxL1dnOTFIUnVZ
        TnpHMkZGSmxYcWFZV1NwT2xSQzVZdEUKLS0tIENwOCtVaVJsSlVYSU5rdFFqQWZL
        aG5uKzE5REt6eldKZFZiZ3Z3dm50dUEK5dRDBn8BhfrQKl1K7xt3b4ZJ6P/kp3Db
        6n5+opYTbsi1NvdPPgdlXlzFg95LzK3EWspdC3vVWzrMVZzxoKZ+Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTWcrc0t3Ynl6V2xEbGdw
        MW1GSFk2b2F4NjNsZUJtWjZpbVRzUEc4cWlzClRFVGdxOHdCcDZENXZFNDNrU1o5
        aDRHZDh0SDE4aXZvTTFUdkZ0Z1MzZ2cKLS0tIHFSdldJcnEvUkpKSVhIdXZ2M0ww
        SlZsTmg4NTZtRUNLbkJZOXRLSG5TQmMKz8WxR438Xor4/QZu/UUYdCtOPU25G0m6
        bl6h0ZvmExYpXFN/GNpJxQbF7e/xiw3Zdb50gaf6tZTR7JB1b0fx4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lklatlu5ce38ra73u3d4el079xh8ltnphkws22xhnr3sgf4mnujsgv7jgv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T13:16:08Z"
  mac: ENC[AES256_GCM,data:/rY5fuL3M3Gwnet4NGusXB+N/81e94Qf+0bISziHyuJopFRGDZ9Zn/2aPgCyPuJLv4Sgaqk7MxTh4QcAFT8z0dytrfdny8XpPyryOXrC82bYcIhXDryKugpiXLtnWNM0N7N7NrDI2ZrTH+yC4XEQeCwV5WNZqk7+Wen17GrOBYA=,iv:sSmvATYQJU6umEw3BMMzLYnmd2WHTTHmM0d2J8Y3JNA=,tag:gqWV7vNQWJPjigcA6RDqqQ==,type:str]
  version: 3.13.2
