#!/usr/bin/env bash

if [ "$EUID" -ne 0 ] ; then
  echo "Please run as root"
  exit 1
fi

read -r -p 'Nuke k3s?, confirm with yes (y/N): ' choice

case "$choice" in
  y|Y|yes|Yes) echo "nuke k3s...";;
  *) exit 0;;
esac

systemctl stop k3s-bootstrap-apps.timer || true
systemctl stop k3s-bootstrap-apps.service || true

flux uninstall -s || true

kubectl delete deployments --all=true -A
kubectl delete statefulsets --all=true -A
kubectl delete ns --all=true -A
kubectl get ns | tail -n +2 | cut -d ' ' -f 1 | xargs -I{} kubectl delete pods --all=true --force=true -n {}

cilium uninstall || true

echo "Waiting until objects are deleted..."

sleep 28
systemctl stop k3s
sleep 2

rm -rf /var/lib/rancher/k3s/
rm -rf /var/lib/cni/networks/cbr0/
[ -d /opt/k3s/data/temp ] && rm -rf /opt/k3s/data/temp/*

sync

echo -e "\n => reboot now to complete k3s cleanup!"
sleep 3
reboot
