apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  TLD: ENC[AES256_GCM,data:lbQsj1gV,iv:YlX9KCxrT1OdokLiFO+qPJ5uJOlWjs5VmIm/BKFxjlI=,tag:5tPceOYcq6v2fdcsAhR+5Q==,type:str]
sops:
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SS9yenpiR3c3VDZ5alhI
        MmR1dmVLeTdUMzU2TGxVQzBGNDNyYUJ6TlFvCmRYaG8vRXR2ditYazJoTHByeDkw
        eXhkWGRGWDJzWVpBdklrMnF1YWpBSDAKLS0tIEY0Qzd6WlErM1hSdElFRDVJR1Nj
        aWVOSkd1R1lBYTJrSGZuZXU4Q1ZaQU0KhIR3wlD3kMwqX5HK25ZPbmzbQwXghEA2
        4AKHPoZ+fBQ10uIGejYFqhlxBTWvwMwHDOAtgr/yT2CcpbHuf/56Dg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUzRnS1ZsODEvcEpqMFlo
        YXdsaWxNZlQxRGlKbmVXR0wydjFYK21KZlRFCkV1Y0RYUDFtQjVUM0h5THVzYUtw
        Nk1ManRrOXNrYjdxUTNDRHdQNE1zTW8KLS0tIGtlUC9rWERxRUFCeG1NemFEc0d3
        T2kxMGVoRkszaGJLQklUUjVDcjNTb0kKbP1fexsibjMtg+c5Oend/69W4LPjLRiU
        sp8tyI5nO390VqZ48EuOA+ZZTgGOJUOWxoKXoKw648h4RVkL/Go8hw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WGo1NDdOUEN4UEZxRUgw
        Mm1NVFBWM0NBL3JUVHJKd0htcmJGaE1WVm40CnBSMDA5ZVVtQXFoMFgzWlhaQit6
        YXZ1M2piREY0TlpmYjJ6NnJsVWdJdTAKLS0tIFFUMWtwMk1CbHpMY002WFoyS3NY
        MHUyM2FXaXpDaDE4ODhlTmxSM0R5WHMKk6oCl4O47yiYhofp6EAvundCvUDmLTBL
        8UR9oepFXXGrlIWkeTQIqS3QVZTpz4973I1uUNbnqJ04tTrv3k1k7A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleFAyUittMklzRWVBeVZ6
        UFRhcWhHcjBPZldIR2t3clNPaTlOM3JmNmtvCkVicEM1cjJqeWNkY0F6Y0t4TW53
        VGVDcTgxeXFDbmkxZ1VtVmFVYkU1ZHMKLS0tIEJ2WTdZTm5XQ01mMTJmYi94dmlp
        Y1dURnJCVjlCTFhCa3BZYlhsSFVtMk0K1HX2Uv/S+7ozXBJLLTgJpz6FrtJa+bCH
        CDvrIBGC4MMrlwid2OpnQpGkQiXkzeBS7dh9J4/6yvXUNt1XmdgAlw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbGhOV3o2Wml5K1NKUGZn
        NWFac3VTcTdVTWZLMDd1WjJJMHdSOEdXbUc0ClltRWIveEhXeDd1TjViWkhWUFdy
        WlhwL3pyS056UDFteXBVaE0zdmRGQkkKLS0tIFZKdDRiSGRKaGt4Tk9BVVMyR01F
        LzBKcXhuTW1mb1VVYlBQNkt4dnprOWsKrQ2D0BgC8IMHe4783ntafuAspeZsRPgX
        WW5ovqeLK3XfAvpcEudtQi9dlHQXgZ0OD/3UNteNnIYH+8qG5tAaSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T15:15:27Z"
  mac: ENC[AES256_GCM,data:PFxRWmCjXjPEZ3YrPRMyOoWtQ8CmWrYVKOL5M9JZiDN0vC6DZIW4AeGz5ism1hDu92yJmvA4LXq1O3a5Kpi5RfkBI+gG/r+ULR6PMI/VN3mO6F9UBYYEU3923EPnTj301tzBpNlZkN+RgAub8gWdK9CTKnQ8EdPa1QFAqtY5azE=,iv:ohAl/tmN5iWWpB0AeZaPd6FTWxjwI4zYZ5RFH35EekM=,tag:UryMivgDvdTqgr7qGsfZbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
