apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qdEvUkVn,iv:IXRSSpu/0AlqRx0NC7pbQXNkxV/GeUN95V0fyCqJ+KQ=,tag:A4wMqYyPxucVHNpbTAwIQw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRTFRYTlLckltMmRKWk9u
        bHVjdjRIbmRFNFZnQlNSZ2JvOEFjQ0FPamtBCjdnS3VEMm9NYngvNzVySDlFaXNB
        a2NvbkNlMlBaYkhZQUlkbmFWRnVZQjQKLS0tIFplSEZBaTZyMHVOY1REUm9vSWNF
        eUVDOGZGT3NWYnN5b0M3eEpuWS9TZ00Kq/8Y44e6SZX3XYvb8fCjFnOlgIefn/ea
        v8Fdbcn7UMAv6BcfzTtenRk+1IIzc6O6lQk+1P5WEHKt6r2A8w2SCg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ekNEMHZhTnowaDIwdng2
        VG9hVGpDRVFHTmJlM2RJdC85N2NZMnJhdVFJCmtINEdZMXlEWVVGQmRnMEN2cnV2
        T1JJVXgzREJMbU9tQkVQTmhqUXZaTWcKLS0tIHVlMWxWdkJ0T3J6bXlxYlYwTzVJ
        dDRIT01mSDFudGhjampUVFU2MGoxOFkKmNNfO0TxIFLvgEPkMqcuyYRydXv3TtHi
        lBShE+VwFZ6pLTqZHeQIkOeYAV9/c6Q8itj27+KyxzaKjYisWcccdg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bXF2TnZWL3JpclVyZFk3
        Y2Z4cGxLZEg5OFNEQlgyNFVlamdnOC9RZEh3CjJ5MkZBaThuY2g3QTJHYjBsR05K
        SlZLZDFoUVM2SkV3OVg3eHJHb3owc1UKLS0tIEN1UFkybUVRY3c4Z0JaNHBrSlJi
        dDNOQ0x2cncxK2VFQnlZclM1Vk5uR0EKf/zjyt9+crrzwY1XVG96Hfo/GpC9dSiW
        epSTkGct/UDf0pYgdfptT/zUMWBr9NdbdfehibMSjvD0SB9yvgpQPg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVTZ1alVLVVdReTRUUU0x
        a3JvNU9URzlvQ3NSMjRETnBXWStDYTUwaWtjCnpVemJVOGRid1d5aUVqL2ZRZGE0
        b2ZsTWd6UGVHVHZqOEFIaDRONmFTZjgKLS0tIGc4V0pOSjVhNEJlUnJmblY0ZEV0
        YThyWXEzY3E0ZE5TMEtUYnl0V2I2TnMKicpBKlBR9H6X4e1mKXm4l8RN0N12nrPO
        V4fHwcZVGTJE40s98joGAsKI1J/AP6TQbknVwffaQqm8wuNp1JZ35Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:P+r9XkpTu3NnRfDAfDNpAH/ElfVlbG3YMKaHbpu7RbLeiUxvb44T7bV1a3bR/uD+cUC98Jm1cZRW9W6y0R0KKdSYogD2bdyvHM17/DsswSOIeqbMa5DBYAgzx0iv408wCUypUTXFTTUEJkHVBpTUz7BVdKuOyPQ3Td7O/cmi7tg=,iv:8zrRGDLCpgsVlyvzjGRoEWsv+WIjJGYj03W8Lsdsmxo=,tag:PFnAARuJ6MUp66DNtoKZaw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
