apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:k+SKMOjahRgIHVHEhKn2AcSQI3w8ixE/aN92/8EH2Fie5kYpLjMH6t0Wsjm+mLZJPx+lOB3NxH7v5dHlgr0Xvr0+Sc+2K5Kwd5Q=,iv:rq4QETpUW4JfS92hXOXvIziDHAnpuoNFhUeF7qrGXs8=,tag:dq8WcZrRn66g4OOLSW/YIg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc2VIdk5wSFYzVmRmdmJE
        RGZxNGtKOEI3L21iUWpHZ01wSU9aTzZJNkFnClBaZFhoeUgxQWZkeXpkRldVM25Y
        V1FuT0doYktCK0YzL3JuOU5yQ2h4ZTgKLS0tIGJMMDVJOGNsZjFBeTlrUk9aSWVL
        YU9MSUVuTWovWHluWXZOeU9sRUVjaUEK9eS23LGm0Q6qUKkb76wm6DtcrFln2Ost
        9t1oTkAz9xko02eN7e6WPudsaKH0m8nbfFB3HmxgUBFHtwxk/1EC0Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb2lzVUh4aFFWT2lNZjdx
        WWNkdHVXYTIrN2xVbG9EYW9FR2twVlFLSWhnCjFXeUcxZ0dJbENvdEFRUEFrbWtG
        cERoNkFNLzVianZMVkVIcVpwVTlqVncKLS0tIFZ5STNsbzZWNlhYaE5nNlhNeXM0
        YU0wSE1HVXpKRDczTk8zcEtWc2dwbjQK6t+fYradl6axU2eUqv8dHXtkV8s8VRPc
        mDwoG2/8zhFNfn+PvqQS86vHg/j1jmjKt+Q8K6FCBT5SWqb3JlwJYg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVzZXRkl1dkgzZ3ZVcjJz
        ajdwTWh4NTc2UTdGVWtEaEpXUkZHV0Z6d3drCkowNmZxekxualdSNUpzR1FiOWFI
        OXBIbkozMEtOTEkvcU5CMFc3bXNCdE0KLS0tIFkrM1BQT1JOTVVBbEN5ZTFNdTV4
        RXEyRmEyd2ZZck5kNVA5eFppQzVoMXcK+fAR4ieJgJQ97awxAa8SVc9H1Yxo7O4v
        MJAOFx3fL3DgSXnUQ3Rl9el25PfllxG7NWNRH+XANHpKk5/eRVupYA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreGJORGppK0VzOVAyWlZ2
        OEp5L0ZlQVY0R1BBQ3M4UDNmaWp0eHRyZjNFCnVPZnBac0NlSlNwN0ZFS1pwYUVF
        MVZBTHkvZDV0T1Y3Y243RVFTL2VjaE0KLS0tIDFNUnQrVWNBdUNOM3MyTHBoS0sw
        Y3NORDJ4NlJmbzBMbjZpL0k5VlpBYkkKqcNUGtmnijhjEi8WdgbNgP76bksWW2VT
        Ttj7eyQkac6+7fNjtRFViIohrFFvTJwXUse85+81Jl1xf8fNS8siJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:eHsxxJTG8lNfeBMTFJo3DobPG9o2XI0pRDLNVzp3PMnQD4FUB22cpoT3fCwhTMA/CcZdEUwlfgmNHXrkewb4vADNsii+HKL60o2NJAm5ppwvEdNv0I2byXtSZuKWHipOmf9TprzXSgnb/pUlYl7ROpkMeUe9R5YCknZTMZcjeuc=,iv:vTYY8FMMzOxi/TeXmGIADJyflnjgNbrRGXFecaKtihY=,tag:7QYNDi8kBdC3A77EqtamXQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
