# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:q++M3TjJ6T6vy8U271AanNHpqqmO4BhjzEzjZroLZ4q5vNNVQgQS8Q==,iv:4WvgBcirVEYD0zkGHjMkZb6Kx31Nesiw5l3+aqpMoQY=,tag:4CVQNvMPUXeC7Kb8gclORw==,type:str]
sops:
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM3FmNEFnUVZ6bStOK21m
        b3Npd0pacllPL3lJY1FJaW5WbUNiQnVUNGowCjBOL2ZOWWdTNllPK3F6Kzg4VmVU
        a05hMFFSeUcxWDdoM0ZHRHFvNldvMlUKLS0tIFMvanlDTVVwcThkSUIrK3ZLcFZa
        MzFmMjNVTWRiQkF1NVpJYU1ja3c5M1kKF7SM4gETZ9xQwy7x2FdWs24DHffgx94F
        g1VoLB+Nap9p+HYUs86t1SUsFLOwPvHgYj2dIKj6aMeBVKNAZ+RhxA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK0x6TFJ0dnhRd2VmTU9k
        dllxaitqYWFuak9GUG1iUHM4aVpVNVBlZlg0Ck9yNjgyY0NxeFFicmM4UE5WcXly
        K2pZNkVOSzlrQStnNWh6NkNDUENIUHcKLS0tICt5RWdjYzRUY3VoRFZweUZvTlFH
        UnpUK2tMd3hKL3ZudFFrZGhBVzBqSlEKYlS+Tb34V58a0F5ZF5pCjPNdLI2KcrCw
        Tf5EJc/a0GAHIiWYHhMvLyJOWZeKnvLLO6vUVBMOj68VOKntbHiMaQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa1Zaa2hYUzY2MWNZREk1
        bjB1UklKR2ZsTklUeFQ1b09Tc2lUK2J0L0R3Cm8vZnVQNXFRVG5oYVFGNUpNc2JI
        RTkzZVZvWjR2L2J0UlZybzNVb0dIVjAKLS0tIGV6YWpMRk0vNzRWVnFXVk41WFJZ
        N3FablRWZWFEVlJodU1uaU1kZUJvNUkKLtfBTwzX/Sxbru2hfP0uonPDjNQ5TQBN
        lCanOgRAWz2XIvWiSa0qLNIEh5e+kNxdzJpXe3Y5OiGUxrHwliyY5w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MUJDbE9LZUY3eVBrbEZv
        dzBiem56WG5xeW93ZTAvQ0pkUVpicXJuT1JnCjU3ZWpoZElxR1ZHbWtnalZYU2d3
        aFdRNVd0aHJjQ1I0cmtPeWY1VTJzRzQKLS0tIHJKSnNlVW5zek5USVdheWpabkQ2
        SFFZREprZEEyTWJ1Z2cvT3RHREYrWUEKpssGU6zasQW6Dh+hixIlBYlG3Sl9JSOL
        qcgACtFwieBGLhcF6HQXt+YUERljRhgcOk9xtUFxKF6iL8aqlXplpQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnhUWWJjdmFpV1RPMGtT
        dWh3dXJ1K2tkdythd2VUNXd3OHRPNVBINGdNCmxLK001M1A1OUhhQzBkVEJhRW9v
        SzIrdE1xUDBSZHNSQ09jTlNxZVBJWUkKLS0tIEhXYmlOZ0VvYkhDK3JtNkkvK0NI
        YVplYjRtdG1LRWI1N05rS1pNZ3poMzQKq2Kbu2ZMAw11SPcPlLCCTJbdufljiw+a
        Q6QsZfwu2fJlnNEGo+s/LIJzqN6eYQaIjwpFXFLy/OAqjJre3uKPug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:XREhBZ+CFD5olEjgiqi3DzIEmhX8J63tMUeQf9lIpxru50bkH4SL1hYlsyCifnSFYejxUtYzb4Ewf+1iL4GFyJfVB6lADPCNW2D0ok+xc4Wl4ROsl9Y+gzYqvcIB/cKMe1pTZFsPYmdVuC4pxmyppu6Huplh9Gp6kfAp7+v9x6E=,iv:S0oqnpUNVFXCTElpfyzF2tsOy80aYru6BpWEEO/iBcc=,tag:JcyzRQpt7wSgI2a6qnd6jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
