# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:q++M3TjJ6T6vy8U271AanNHpqqmO4BhjzEzjZroLZ4q5vNNVQgQS8Q==,iv:4WvgBcirVEYD0zkGHjMkZb6Kx31Nesiw5l3+aqpMoQY=,tag:4CVQNvMPUXeC7Kb8gclORw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1lvcgfp9v4kj24zyr5rkuchzmhkaxhjqhlkyqstscn0m7glkdt4ns7ye6eg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UnhRQndrU1V2MURUVFhK
        SE00VjllMit1azRBdnBpV0pWWlYyT0tEQndRClpOd3M3K3Y3SkU3QndndnNtZFJJ
        ekNYQWlhS2FBbUtGZjFkSVVpVU5UWncKLS0tIDZvWWpRWHE3ZjNETWdNSnNsT3d2
        Mkl3MW4zUUk3NzcwV01TLzZVc3hxcUEKgKrd2fjkcjP4L/Jh2HelbOFftSBWTLyV
        i/kkGo//D9WC3KgmglgNt6A/4Xu7BwXQkrdIMfzU9QSJSfWq2mkCnw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1ux98gnft3k34lpqrqu6ayjvc3zmdltv5wdf3kxnhnd2y6srjjulqllfecm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCalV2K3BMSXhadG1BWklH
        cVdNMzUzK2gxTGY3MVdnRFFSTFVYb043VnhrCm9OYVFJR1NGRDlhSi9IQWRsZEE2
        L3dHVVZ1ZkdONkFna0F0eENKR2NmWU0KLS0tIDJnYlI3RzVwa2UzcDVQbEVGWm5Y
        ckY3K0FTTTB3eVEydDY4Ylp1MHdTT1UKxPCnmC7fRhlKe29dyIF1COSCpu1Wbyx1
        V18VMz8pae/j/jqH+dK61I/p3aJV6Lz5CnQVWSXkPAPPdh67Bbk0sQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age17kz6tccq4sfu07mwuqkmy9sgr4np3g2cdjejj3a3j7qud2nfepdqkyee7y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QnAzNHhheHdiQkdZcndp
        bkIyOVhyWnFFeXNrNFpKSUVEa0dlZFNNUkNRCnJZenhWZHZXQk45QmNqVm1USHB5
        NGRTOEZ5VWdYdUVORC85Q2JzbXVLRzgKLS0tIENoNFhOTlUvOFhTazdLT2ZMSUxT
        V0lPa0tpNGVoTTJVWUcrZ3VRODhibzgKQAorGU6Bz27cLAdncNjsbCqQIfKBjfvR
        Fxl4OBkCoXrtYc10Athy6qhlPa/HPEYCwfPOzjekceevXdLG6ImBvA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1dhsru3z3hdv2f9h9js43k083gqxaas3vtm8uleq3t9gtkchrcgwsz07px5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVVZYNDZ6bldkdTVlQ0py
        K1ROb3pxTHp1WFVyaC9kQzhzWmhzYkVwQkhvCkdBM1BqaUxGZ3BkZjVHUFlqem1h
        d3RjcXJ2aityakxJV1ZBRjdrL2FEK3cKLS0tIG1ib0F0TVpDbXNZNmtXRGIralFn
        c21ZeTJKSTIweUNuZ0VZM2NwcHVmWk0K9zJ5GHHCot+zOgvb22+X8CcKuxSggQrK
        F/4sfSBFnBoI4uuUUuOelghnh4k12uQJcMY5vah/T9HNRC78vQvDUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-23T18:56:24Z"
  mac: ENC[AES256_GCM,data:XREhBZ+CFD5olEjgiqi3DzIEmhX8J63tMUeQf9lIpxru50bkH4SL1hYlsyCifnSFYejxUtYzb4Ewf+1iL4GFyJfVB6lADPCNW2D0ok+xc4Wl4ROsl9Y+gzYqvcIB/cKMe1pTZFsPYmdVuC4pxmyppu6Huplh9Gp6kfAp7+v9x6E=,iv:S0oqnpUNVFXCTElpfyzF2tsOy80aYru6BpWEEO/iBcc=,tag:JcyzRQpt7wSgI2a6qnd6jg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
