---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
spec:
  dependsOn:
    - name: authentik-db
    - name: envoy-config
      namespace: network
  interval: 1h
  path: ./src/kubernetes/apps/auth/authentik/app
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: auth
  # must outlast the HelmRelease's 15m upgrade timeout
  timeout: 16m
  wait: true
