---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-tunnel-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: *name
  data:
    - secretKey: tunnel_token
      remoteRef:
        key: cf-tunnel-idp
        property: password
