toml-version = "v1.1.0"

[files]
  include              = [ "**/*.toml" ]
  respect-ignore-files = true

[format]
  [format.rules]
    array-bracket-space-width       = 1
    array-comma-space-width         = 1
    comment-style                   = "normalize"
    indent-style                    = "space"
    indent-sub-tables               = true
    indent-table-key-value-pairs    = true
    inline-table-brace-space-width  = 1
    key-quote-style                 = "double"
    key-value-equals-sign-alignment = true
    line-width                      = 88
    string-quote-style              = "double"
    trailing-comment-alignment      = true
