---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./namespace.yaml
  - ./actual/actual.ks.yaml
  - ./linkding/linkding.ks.yaml
  - ./n8n/n8n.ks.yaml
  - ./split-pro/split-pro-db.ks.yaml
  - ./split-pro/split-pro.ks.yaml
