---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: actual-secret
  data:
    - secretKey: ACTUAL_OPENID_CLIENT_ID
      remoteRef:
        key: Authentik OAuth
        property: actual-client-id
    - secretKey: ACTUAL_OPENID_CLIENT_SECRET
      remoteRef:
        key: Authentik OAuth
        property: actual-client-secret
