apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-credentials
  namespace: external-secrets
type: Opaque
data:
  1password-credentials.json: ENC[AES256_GCM,data:wwff2zKeBHBaSdqbwcKioys2bjAkdSvor8wJ5r6wQ2KTvMLI7qGOnzjBFQftA9w=,iv:QUqs0iudir2qjoGFpGWDq2Whf+zF8aNek59lN49WdIc=,tag:WsJAMJno95oRic1tAVirwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMFlDY0RvTGQ0aFpZL055
        VWhxc2xDL01uVHdISGp2MzBldEx6NzhBblNzCjgvVFV4OFl2UG82Q1JoUnNJQmJJ
        S2FzNmNVQlZ1QkdrdVFnQjZxNWd3cmcKLS0tICt0U2pHT2NVczBnOERseUUrUHJy
        L2FjWUFPLzc1MGx0d2RTcU9vMFNGNW8K4tAq9IBymjJ97nj8Lp2TzSX2Saqj9+7N
        ZoKcdrGBbO1EH64W0lHUpPfEJ1PWs4INlVsJAhBMnsbkXY4FoBqUBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8qp0vlv4myatfd0fnm0a2tayu3pf0se4rymmegjrg0sgtucnqeqr66l0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSkhRdEhFUDUydUx4U2lG
        czF4REFOaHZ2enNiL1BjZllvZnZnQzU0Ymx3Ck9sNzdFaTZBQWQ0MTd3UFNOMGty
        aW5pR2UxUHFYR0x3YS9sNm92RVlDUVUKLS0tIGt1cktiSDY1T2RMZmVKdjVRYmN2
        dUhCMlVDdm9DQmQvTjErKzRWYmZaSzQKKsL6zQateZsyp8mIsK+fXHRZ4D3R09cp
        bR3z/8OIyPl1L3+nGSHu757OTdb4YNwsd7mCQ+8N7UPF9/Vr2gHRsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK0lRMGlvZW5jU0lJSWN4
        TEZMVVJPL2R0Z21KOXpnby9Idms1anE0eTE0Ckg4ZnN6Ly9EOGh2Y2VZSzNJczFk
        WmhSbjVoSUhndEhmSWhtZ1lsTWRyZ0UKLS0tIG9DTmtzazliYjE0MkpJU0NiU251
        UERQTUZIWGhxWUtyUERkUlFCWERIVlUKuHlFrTnIbafE+6Y1eqIfrr+k/WLaTe8F
        x9W1nga6jyzlQvaWRH3Q5uR4a86vyYeThomCi4gA9q4+BE/eDExrRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k3qx2cy4662hpe4g6038a8f5fguzum8mk5rhvgszqq3j0yt923tqsue8z9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T13:16:24Z"
  mac: ENC[AES256_GCM,data:UJvmPm0zDfW5wgY9Spw0HjDAOU36K4Ho3L+qDmORu2GghrIBCQMcKKUcw58uGXQKKV0ggmCFcqvzmiAwe/TW1KnQLmaoKX1xoeL4EwN2nHrZ8881mJawdu8IgROs8w2OMF89E6VZt7EFFC1sSmJL42emBli81qQhbx91e+q3Ckw=,iv:2/bOzKLPS32ibIJODchpvNys0o5FXCrlAr9qa7JBqoA=,tag:J5b/EPmh5OYUwDdGqzE5sg==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: op-connect-ro
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:geBTbw7jHIpUoWwYy0G+5BuGs/fURTbFRhVcoDw=,iv:avNe4cqQQXjVoyYYziXsqUXENWNcwje74vab0Ev23po=,tag:8lSwVP1BuYlJ4mGHbVQtPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMFlDY0RvTGQ0aFpZL055
        VWhxc2xDL01uVHdISGp2MzBldEx6NzhBblNzCjgvVFV4OFl2UG82Q1JoUnNJQmJJ
        S2FzNmNVQlZ1QkdrdVFnQjZxNWd3cmcKLS0tICt0U2pHT2NVczBnOERseUUrUHJy
        L2FjWUFPLzc1MGx0d2RTcU9vMFNGNW8K4tAq9IBymjJ97nj8Lp2TzSX2Saqj9+7N
        ZoKcdrGBbO1EH64W0lHUpPfEJ1PWs4INlVsJAhBMnsbkXY4FoBqUBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8qp0vlv4myatfd0fnm0a2tayu3pf0se4rymmegjrg0sgtucnqeqr66l0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSkhRdEhFUDUydUx4U2lG
        czF4REFOaHZ2enNiL1BjZllvZnZnQzU0Ymx3Ck9sNzdFaTZBQWQ0MTd3UFNOMGty
        aW5pR2UxUHFYR0x3YS9sNm92RVlDUVUKLS0tIGt1cktiSDY1T2RMZmVKdjVRYmN2
        dUhCMlVDdm9DQmQvTjErKzRWYmZaSzQKKsL6zQateZsyp8mIsK+fXHRZ4D3R09cp
        bR3z/8OIyPl1L3+nGSHu757OTdb4YNwsd7mCQ+8N7UPF9/Vr2gHRsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK0lRMGlvZW5jU0lJSWN4
        TEZMVVJPL2R0Z21KOXpnby9Idms1anE0eTE0Ckg4ZnN6Ly9EOGh2Y2VZSzNJczFk
        WmhSbjVoSUhndEhmSWhtZ1lsTWRyZ0UKLS0tIG9DTmtzazliYjE0MkpJU0NiU251
        UERQTUZIWGhxWUtyUERkUlFCWERIVlUKuHlFrTnIbafE+6Y1eqIfrr+k/WLaTe8F
        x9W1nga6jyzlQvaWRH3Q5uR4a86vyYeThomCi4gA9q4+BE/eDExrRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k3qx2cy4662hpe4g6038a8f5fguzum8mk5rhvgszqq3j0yt923tqsue8z9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T13:16:24Z"
  mac: ENC[AES256_GCM,data:UJvmPm0zDfW5wgY9Spw0HjDAOU36K4Ho3L+qDmORu2GghrIBCQMcKKUcw58uGXQKKV0ggmCFcqvzmiAwe/TW1KnQLmaoKX1xoeL4EwN2nHrZ8881mJawdu8IgROs8w2OMF89E6VZt7EFFC1sSmJL42emBli81qQhbx91e+q3Ckw=,iv:2/bOzKLPS32ibIJODchpvNys0o5FXCrlAr9qa7JBqoA=,tag:J5b/EPmh5OYUwDdGqzE5sg==,type:str]
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: op-connect-rw
  namespace: external-secrets
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:Muc/juhVp4UYoPble2kYpfdTHqB9RW1QpyocCEyydrnp0qo=,iv:AxmUXmhvJdq+zGe0mvd0AjY+jzrV6dnoIvNs3vpc0y8=,tag:I+TjERT4dJ53EearlCpuCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMFlDY0RvTGQ0aFpZL055
        VWhxc2xDL01uVHdISGp2MzBldEx6NzhBblNzCjgvVFV4OFl2UG82Q1JoUnNJQmJJ
        S2FzNmNVQlZ1QkdrdVFnQjZxNWd3cmcKLS0tICt0U2pHT2NVczBnOERseUUrUHJy
        L2FjWUFPLzc1MGx0d2RTcU9vMFNGNW8K4tAq9IBymjJ97nj8Lp2TzSX2Saqj9+7N
        ZoKcdrGBbO1EH64W0lHUpPfEJ1PWs4INlVsJAhBMnsbkXY4FoBqUBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1s8qp0vlv4myatfd0fnm0a2tayu3pf0se4rymmegjrg0sgtucnqeqr66l0d
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSkhRdEhFUDUydUx4U2lG
        czF4REFOaHZ2enNiL1BjZllvZnZnQzU0Ymx3Ck9sNzdFaTZBQWQ0MTd3UFNOMGty
        aW5pR2UxUHFYR0x3YS9sNm92RVlDUVUKLS0tIGt1cktiSDY1T2RMZmVKdjVRYmN2
        dUhCMlVDdm9DQmQvTjErKzRWYmZaSzQKKsL6zQateZsyp8mIsK+fXHRZ4D3R09cp
        bR3z/8OIyPl1L3+nGSHu757OTdb4YNwsd7mCQ+8N7UPF9/Vr2gHRsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ev6jd40jw3eu3z2xwea2gyxr68t540dwt433r9tj8c8xdjc50aassdg0cu
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK0lRMGlvZW5jU0lJSWN4
        TEZMVVJPL2R0Z21KOXpnby9Idms1anE0eTE0Ckg4ZnN6Ly9EOGh2Y2VZSzNJczFk
        WmhSbjVoSUhndEhmSWhtZ1lsTWRyZ0UKLS0tIG9DTmtzazliYjE0MkpJU0NiU251
        UERQTUZIWGhxWUtyUERkUlFCWERIVlUKuHlFrTnIbafE+6Y1eqIfrr+k/WLaTe8F
        x9W1nga6jyzlQvaWRH3Q5uR4a86vyYeThomCi4gA9q4+BE/eDExrRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k3qx2cy4662hpe4g6038a8f5fguzum8mk5rhvgszqq3j0yt923tqsue8z9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T13:16:24Z"
  mac: ENC[AES256_GCM,data:UJvmPm0zDfW5wgY9Spw0HjDAOU36K4Ho3L+qDmORu2GghrIBCQMcKKUcw58uGXQKKV0ggmCFcqvzmiAwe/TW1KnQLmaoKX1xoeL4EwN2nHrZ8881mJawdu8IgROs8w2OMF89E6VZt7EFFC1sSmJL42emBli81qQhbx91e+q3Ckw=,iv:2/bOzKLPS32ibIJODchpvNys0o5FXCrlAr9qa7JBqoA=,tag:J5b/EPmh5OYUwDdGqzE5sg==,type:str]
  version: 3.13.2
