---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./namespace.yaml
  - ./certificates/certificates.ks.yaml
  - ./cilium/cilium-bgp.ks.yaml
  - ./cilium/cilium-network-policies.ks.yaml
  - ./envoy-gateway/envoy-gateway.ks.yaml
  - ./envoy-gateway/envoy-config.ks.yaml
  - ./echo/echo.ks.yaml
