---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-connect-ro
  target:
    name: n8n-secret
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: Authentik OAuth
        property: n8n-client-id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: Authentik OAuth
        property: n8n-client-secret
